import { AccessService } from '../common/access.service';
export declare class PeopleService {
    private access;
    constructor(access: AccessService);
    create(treeId: string, data: Record<string, unknown>, creatorId: string): Promise<{
        id: string;
        created_at: Date;
        first_name: string;
        last_name: string | null;
        maiden_name: string | null;
        nicknames: string[];
        gender: string | null;
        birth_date: Date | null;
        birth_date_precision: string | null;
        birth_place: string | null;
        death_date: Date | null;
        death_date_precision: string | null;
        death_place: string | null;
        is_living: boolean;
        bio: string | null;
        occupation: string | null;
        religion: string | null;
        nationality: string | null;
        languages: string[];
        cause_of_death: string | null;
        burial_place: string | null;
        tree_id: string;
        created_by: string | null;
        updated_at: Date;
    }>;
    findAll(treeId: string, userId: string): Promise<{
        id: string;
        created_at: Date;
        first_name: string;
        last_name: string | null;
        maiden_name: string | null;
        nicknames: string[];
        gender: string | null;
        birth_date: Date | null;
        birth_date_precision: string | null;
        birth_place: string | null;
        death_date: Date | null;
        death_date_precision: string | null;
        death_place: string | null;
        is_living: boolean;
        bio: string | null;
        occupation: string | null;
        religion: string | null;
        nationality: string | null;
        languages: string[];
        cause_of_death: string | null;
        burial_place: string | null;
        tree_id: string;
        created_by: string | null;
        updated_at: Date;
    }[]>;
    findOne(id: string, userId: string): Promise<{
        media: {
            id: string;
            created_at: Date;
            type: string;
            tree_id: string;
            person_id: string | null;
            uploaded_by: string;
            file_url: string;
            thumbnail_url: string | null;
            caption: string | null;
            taken_date: Date | null;
        }[];
        relationships_as_a: {
            id: string;
            created_at: Date;
            person_a_id: string;
            person_b_id: string;
            type: string;
            start_date: Date | null;
            end_date: Date | null;
            status: string | null;
            tree_id: string;
        }[];
        relationships_as_b: {
            id: string;
            created_at: Date;
            person_a_id: string;
            person_b_id: string;
            type: string;
            start_date: Date | null;
            end_date: Date | null;
            status: string | null;
            tree_id: string;
        }[];
        life_events: {
            id: string;
            created_at: Date;
            type: string;
            title: string;
            description: string | null;
            event_date: Date | null;
            place: string | null;
            person_id: string;
        }[];
    } & {
        id: string;
        created_at: Date;
        first_name: string;
        last_name: string | null;
        maiden_name: string | null;
        nicknames: string[];
        gender: string | null;
        birth_date: Date | null;
        birth_date_precision: string | null;
        birth_place: string | null;
        death_date: Date | null;
        death_date_precision: string | null;
        death_place: string | null;
        is_living: boolean;
        bio: string | null;
        occupation: string | null;
        religion: string | null;
        nationality: string | null;
        languages: string[];
        cause_of_death: string | null;
        burial_place: string | null;
        tree_id: string;
        created_by: string | null;
        updated_at: Date;
    }>;
    update(id: string, data: Record<string, unknown>, userId: string): Promise<{
        id: string;
        created_at: Date;
        first_name: string;
        last_name: string | null;
        maiden_name: string | null;
        nicknames: string[];
        gender: string | null;
        birth_date: Date | null;
        birth_date_precision: string | null;
        birth_place: string | null;
        death_date: Date | null;
        death_date_precision: string | null;
        death_place: string | null;
        is_living: boolean;
        bio: string | null;
        occupation: string | null;
        religion: string | null;
        nationality: string | null;
        languages: string[];
        cause_of_death: string | null;
        burial_place: string | null;
        tree_id: string;
        created_by: string | null;
        updated_at: Date;
    }>;
    delete(id: string, userId: string): Promise<{
        id: string;
        created_at: Date;
        first_name: string;
        last_name: string | null;
        maiden_name: string | null;
        nicknames: string[];
        gender: string | null;
        birth_date: Date | null;
        birth_date_precision: string | null;
        birth_place: string | null;
        death_date: Date | null;
        death_date_precision: string | null;
        death_place: string | null;
        is_living: boolean;
        bio: string | null;
        occupation: string | null;
        religion: string | null;
        nationality: string | null;
        languages: string[];
        cause_of_death: string | null;
        burial_place: string | null;
        tree_id: string;
        created_by: string | null;
        updated_at: Date;
    }>;
}
